{
 "title": "Subscriber Insigth",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "subscriberUser",
    "label": "Subscriber ID",
    "query": {
     "query": "label_values({source=~\"nok-bng/clab-sros-bngt-bng1|nok-bng/clab-sros-bngt-bng2\"},subscriber_subscriber_id)"
    }
   },
   {
    "name": "bngRouter",
    "label": "BNG",
    "query": {
     "query": "label_values({source=~\"nok-bng/clab-sros-bngt-bng1|nok-bng/clab-sros-bngt-bng2\"},source)"
    }
   },
   { "name": "DS_LOKI", "label": "DS_LOKI", "query": "loki" },
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Sessions UP-TIME",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(state_subscriber_mgmt_subscriber_sla_profile_instance_session_up_time{subscriber_subscriber_id=\"$subscriberUser\", source=\"$bngRouter\"})/100",
     "legendFormat": "Inst. ID: {{sla_profile_instance_id}}"
    }
   ]
  },
  {
   "title": "Forwarding State",
   "type": "stat",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_subscriber_mgmt_subscriber_sla_profile_instance_session_ipv4_forwarding_state{subscriber_subscriber_id=\"$subscriberUser\", source=\"$bngRouter\"}",
     "legendFormat": "IPv4 {{source}}"
    },
    {
     "expr": "state_subscriber_mgmt_subscriber_sla_profile_instance_session_ipv6_slaac_forwarding_state{subscriber_subscriber_id=\"$subscriberUser\", source=\"$bngRouter\"}",
     "legendFormat": "IPv6 SLAAC {{source}}"
    },
    {
     "expr": "state_subscriber_mgmt_subscriber_sla_profile_instance_session_ipv6_pd_forwarding_state{subscriber_subscriber_id=\"$subscriberUser\", source=\"$bngRouter\"}",
     "legendFormat": "IPV6 PD {{source}}"
    }
   ]
  },
  {
   "title": "Egress Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(state_subscriber_mgmt_subscriber_sla_profile_instance_egress_qos_statistics_out_exceed_profile_forwarded_octets{subscriber_subscriber_id=\"$subscriberUser\", source=\"$bngRouter\"}[60s]) * 8 / 60000\n",
     "legendFormat": "{{source}} Inst. ID: {{sla_profile_instance_id}}"
    }
   ]
  },
  {
   "title": "IPv4 Address Allocation",
   "type": "logs",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"gnmic-state\"} \n|= \"ipv4/ip-address\" \n| json prefix=\"prefix\" \n| json bngRouter=\"source\" \n| json address=\"updates[0].values.address\" \n| regexp `.*subscriber-id=(?P<subscriber_id>[^]]+)` \n| bngRouter =~ \".*$bngRouter.*\" \n| subscriber_id = \"$subscriberUser\" \n| json subName=`[\"subscription-name\"]`\n| json time = \"time\" \n| line_format \"{{.time}} {{if contains \\\"on-change\\\" .subName}}(on-change){{end}}{{if contains \\\"sample\\\" .subName}}(sample){{end}} {{if .address}}{{.address}}{{else}}deleted{{end}}\""
    }
   ]
  },
  {
   "title": "IPv6 SLAAC",
   "type": "logs",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"gnmic-state\"} \n|= \"ipv6/slaac\" \n| json prefix=\"prefix\" \n| json bngRouter=\"source\" \n| json address=\"updates[0].values.address\" \n| regexp `.*subscriber-id=(?P<subscriber_id>[^]]+)` \n| bngRouter =~ \".*$bngRouter.*\" \n| subscriber_id = \"$subscriberUser\" \n| json subName=`[\"subscription-name\"]`\n| json time = \"time\" \n| line_format \"{{.time}} {{if contains \\\"on-change\\\" .subName}}(on-change){{end}}{{if contains \\\"sample\\\" .subName}}(sample){{end}} {{if .address}}{{.address}}{{else}}deleted{{end}}\""
    }
   ]
  },
  {
   "title": "Ingress Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "rate(state_subscriber_mgmt_subscriber_sla_profile_instance_ingress_qos_statistics_out_profile_forwarded_octets{subscriber_subscriber_id=\"$subscriberUser\", source=\"$bngRouter\"}[60s]) * 8 / 60000\n",
     "legendFormat": "{{source}} Inst. ID: {{sla_profile_instance_id}}"
    }
   ]
  },
  {
   "title": "IPv6 PD Prefix",
   "type": "logs",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"gnmic-state\"} \n|= \"ipv6/pd\" \n| json prefix=\"prefix\" \n| json bngRouter=\"source\" \n| json address=\"updates[0].values.prefix\" \n| json prefix=\"prefix\" \n| regexp `.*subscriber-id=(?P<subscriber_id>[^]]+)` \n| bngRouter =~ \".*$bngRouter.*\" \n| subscriber_id = \"$subscriberUser\" \n| json subName=`[\"subscription-name\"]`\n| json time = \"time\" \n| line_format \"{{.time}} {{if contains \\\"on-change\\\" .subName}}(on-change){{end}}{{if contains \\\"sample\\\" .subName}}(sample){{end}} {{if .address}}{{.address}}{{else}}deleted{{end}}\""
    }
   ]
  },
  {
   "title": "IPv6 DHCPv6 Client",
   "type": "logs",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"gnmic-state\"} \n|= \"ipv6/dhcp6-lease\"  \n| json prefix=\"prefix\" \n| json bngRouter=\"source\" \n| json address=`updates[0].values[\"client-address\"]` \n| regexp `.*subscriber-id=(?P<subscriber_id>[^]]+)` \n| bngRouter =~ \".*$bngRouter.*\" \n| subscriber_id = \"$subscriberUser\" \n| json time = \"time\" \n| json subName=`[\"subscription-name\"]`\n| line_format \"{{.time}} {{if contains \\\"on-change\\\" .subName}}(on-change){{end}}{{if contains \\\"sample\\\" .subName}}(sample){{end}} {{if .address}}{{.address}}{{else}}deleted{{end}}\""
    }
   ]
  }
 ]
}